name: deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: pull code
        uses: appleboy/ssh-action@master
        env:
          SERVER_WORKDIR: ${{ secrets.SERVER_WORKDIR }}
        with:
          host: ${{ secrets.SERVER_HOST }} # 下面三个配置与上面一样
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          envs: SERVER_WORKDIR
          # 进入到项目目录，执行依赖更新
          script: |
            cd $SERVER_WORKDIR
            git checkout .
            git pull
            npm run build
            pm2 restart emo